### ISSUE TITLE
Support for `ariaRole` property of the JS class

### ISSUE THREAD

**Issue by jelhan** [ember-codemods/tagless-ember-components-codemod#49]
```js
export default Component.extend({
  ariaRole: "button",
});
```

should be converted to

```hbs
<div role="button"></div>
```

**Comment by Turbo87** [comment]
hmm, why? do Ember components do this by default?

**Comment by jelhan** [comment]
`@ember/component` have a [`ariaRole` property](https://api.emberjs.com/ember/3.15/classes/Component/properties/ariaRole?anchor=ariaRole) that does this. The API of `@ember/component`'s is huge. :roll_eyes:

**Comment by Turbo87** [comment]
huh, I've never seen that before 😅
